version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        dependency-type: development
  - package-ecosystem: pip
    directory: /tests
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /services/gateway
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /infra/docker
    schedule:
      interval: weekly
