import type { SdgPriority } from "./types";

export const sdgPriorities: SdgPriority[] = [
  {
    sdg: "SDG 10",
    name: "Reduced Inequalities",
    priority: "P0",
    fit: "core",
    repoCanDo: "Audit whether public AI services exclude people by age, disability, language, geography, or digital access barriers.",
    proofPath: "REST/Connect assessments plus ERH fallback scoring and persona barriers",
    implementation: ["Inclusion score", "fairness risk label", "persona-specific gaps", "recommended mitigations"],
  },
  {
    sdg: "SDG 16",
    name: "Peace, Justice and Strong Institutions",
    priority: "P0",
    fit: "core",
    repoCanDo: "Create auditable, API-backed trust evidence for government AI decisions and agent safety controls.",
    proofPath: "OpenAPI docs, API-key protected gateway, ADM safety events, webhook signing",
    implementation: ["Swagger/OpenAPI", "ADM event ingestion", "WebSocket evidence feed", "API-key protected surfaces"],
  },
  {
    sdg: "SDG 9",
    name: "Industry, Innovation and Infrastructure",
    priority: "P0",
    fit: "core",
    repoCanDo: "Provide reusable AI trust infrastructure across REST, GraphQL, WebSocket, Connect-RPC, MCP, MQTT, and UCP.",
    proofPath: "Seven protocol adapters over one CQRS trust core",
    implementation: ["Shared gateway client", "multi-service Back4App roots", "Connect-RPC methods", "MCP tools"],
  },
  {
    sdg: "SDG 11",
    name: "Sustainable Cities and Communities",
    priority: "P0",
    fit: "core",
    repoCanDo: "Evaluate city services such as care navigation, disaster support, and accessible mobility for inclusive delivery.",
    proofPath: "Care and disaster use cases mapped to open data and vulnerable personas",
    implementation: ["Service scenario dashboard", "open-data readiness", "disaster-access use case", "care-navigation use case"],
  },
  {
    sdg: "SDG 3",
    name: "Good Health and Well-Being",
    priority: "P1",
    fit: "strong",
    repoCanDo: "Check care-service AI for accessibility, safe referrals, and agent-mediated purchasing risks.",
    proofPath: "Care navigation scenario and UCP care-product trust gate",
    implementation: ["Care personas", "UCP checkout fairness gate", "human review safeguards"],
  },
  {
    sdg: "SDG 4",
    name: "Quality Education",
    priority: "P1",
    fit: "strong",
    repoCanDo: "Audit AI learning tools for access gaps, accommodation needs, teacher override, and regional infrastructure barriers.",
    proofPath: "Education access auditor scenario",
    implementation: ["Education use case", "student accessibility persona", "bias drift safeguards"],
  },
  {
    sdg: "SDG 17",
    name: "Partnerships for the Goals",
    priority: "P1",
    fit: "strong",
    repoCanDo: "Expose a common trust API that agencies, civic partners, and AI agents can integrate without sharing raw sensitive data.",
    proofPath: "OpenAPI, GraphQL read model, MCP tools, and shared client package",
    implementation: ["Swagger page", "GraphQL assessments", "MCP list/evaluate tools", "shared TypeScript client"],
  },
  {
    sdg: "SDG 12",
    name: "Responsible Consumption and Production",
    priority: "P1",
    fit: "strong",
    repoCanDo: "Gate delegated shopping and procurement flows against price gouging and inaccessible product descriptions.",
    proofPath: "UCP commerce module",
    implementation: ["UCP sessions", "catalog discovery", "checkout intent trust verdicts"],
  },
  {
    sdg: "SDG 13",
    name: "Climate Action",
    priority: "P2",
    fit: "adjacent",
    repoCanDo: "Apply the disaster-support workflow to climate hazard alerts and resilient-service routing.",
    proofPath: "Disaster prevention scenario using weather alerts and shelter capacity feeds",
    implementation: ["Disaster-access use case", "source-grounded safeguards", "critical-alert escalation"],
  },
  {
    sdg: "SDG 1",
    name: "No Poverty",
    priority: "P2",
    fit: "adjacent",
    repoCanDo: "Audit eligibility and benefit-navigation AI for people with low digital access or fragmented agency journeys.",
    proofPath: "Persona barriers and service matching metrics",
    implementation: ["Target-user barriers", "plain-language matching", "fairness gap recommendations"],
  },
  {
    sdg: "SDG 2",
    name: "Zero Hunger",
    priority: "P2",
    fit: "adjacent",
    repoCanDo: "Adapt the service-matching assessment to food aid, school meals, and emergency supply routing.",
    proofPath: "Open-data source readiness plus disaster resource matching",
    implementation: ["Resource matching", "open-data readiness", "critical service escalation"],
  },
  {
    sdg: "SDG 5",
    name: "Gender Equality",
    priority: "P2",
    fit: "adjacent",
    repoCanDo: "Add gender-sensitive personas and measure whether AI services create different access or safety outcomes.",
    proofPath: "Persona model supports needs/barriers and ERH-style fairness checks",
    implementation: ["Persona expansion", "fairness-risk scoring", "human review for high-risk cases"],
  },
  {
    sdg: "SDG 6",
    name: "Clean Water and Sanitation",
    priority: "P3",
    fit: "monitor",
    repoCanDo: "Evaluate water-service chatbots or outage guidance for accessible, multilingual, source-grounded public communication.",
    proofPath: "Same assessment shell as disaster/city services",
    implementation: ["Open-data provenance", "localized guidance", "service accessibility checks"],
  },
  {
    sdg: "SDG 7",
    name: "Affordable and Clean Energy",
    priority: "P3",
    fit: "monitor",
    repoCanDo: "Assess energy-assistance AI for eligibility fairness, plain-language recommendations, and rural access gaps.",
    proofPath: "Benefit navigation pattern",
    implementation: ["Eligibility-aid scenario", "persona barriers", "open-data readiness"],
  },
  {
    sdg: "SDG 8",
    name: "Decent Work and Economic Growth",
    priority: "P3",
    fit: "monitor",
    repoCanDo: "Review workforce-service AI for fair access to training, job matching, and agent tool-use safety.",
    proofPath: "Service assessment plus ADM tool-policy telemetry",
    implementation: ["Tool-call policy enforcement", "fairness-risk scoring", "partner review API"],
  },
  {
    sdg: "SDG 14",
    name: "Life Below Water",
    priority: "P3",
    fit: "monitor",
    repoCanDo: "Support public reporting or compliance-assistant AI where source-grounding and audit trails matter.",
    proofPath: "Governance and open-data provenance controls",
    implementation: ["Open-data checks", "MCP trust tools", "audit evidence"],
  },
  {
    sdg: "SDG 15",
    name: "Life on Land",
    priority: "P3",
    fit: "monitor",
    repoCanDo: "Support environmental-service AI audits for transparent recommendations, reliable data sources, and safe agent actions.",
    proofPath: "Same governance trust gateway surfaces",
    implementation: ["Open-data readiness", "ADM safety events", "Swagger integration for partners"],
  },
];

export const priorityOrder = ["P0", "P1", "P2", "P3"] as const;
